Add tests for signature schemes
monadicus/mentat pull request #89
Opened 2022-04-12 23:51 UTC by jels-boolean

Fixes #40 

Time taken: 3 hours

2022-04-21 19:22 UTC, mowkoshka requested changes

2022-04-21 19:23 UTC, gluax commented on mentat/Cargo.toml
> -snarkvm-algorithms = { version="0.8", optional = true, default-features = false }
My bad I never published this when I initially reviewed like a week ago :)

2022-04-21 19:23 UTC, mowkoshka commented on mentat/Cargo.toml
> -snarkvm-algorithms = { version="0.8", optional = true, default-features = false }
My bad I never published this when I did the review a week ago :)

2022-05-02 21:16 UTC, jels-boolean commented on mentat/Cargo.toml
> -snarkvm-algorithms = { version="0.8", optional = true, default-features = false }
I had a ton of compilation errors trying to get this to work and switching the features on actually made them disappear - I will look at what i can disable though.

2022-05-04 20:44 UTC, jels-boolean commented on mentat/Cargo.toml
> -snarkvm-algorithms = { version="0.8", optional = true, default-features = false }
I've tested all crates, I could only remove default features for snarkvm algorithms and nothing else. These crates only get pulled in if needed through a feature flag anyways so it shouldn't be a big deal.

2022-05-05 18:17 UTC, mowkoshka approved these changes

2022-05-05 18:46 UTC, merged